spring.application.name=adminsecudre
#spring.security.user.name=raj
#spring.security.user.password=raj

jwt.secret=afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf
jwt.expiration=3600000


spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.bnlmvwtstzfevjnupjfz
spring.datasource.password=im24Faisal@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=org.postgresql.Driver




#jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres?user=postgres.bnlmvwtstzfevjnupjfz&password=[YOUR-PASSWORD]

#host=aws-0-ap-northeast-2.pooler.supabase.com
#port=5432
#database=postgres
#user=postgres.bnlmvwtstzfevjnupjfz